
doctrine:
 
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        #driver_class: Realestate\MssqlBundle\Driver\PDODblib\Driver
        driver: 'pdo_mysql'
        host: 127.0.0.1
       
        dbname: projetsec
        user: root
       
  
     
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App